name: Deploy the Backend
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout the code
         uses: actions/checkout@v2

       - name: Docker login
         uses: docker/login-action@v2
         with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN}}

       - name: Build and push ##docker build then docker push
         uses: docker/build-push-action@v4
         with:
           context: .
           file: ./docker/Dockerfile.backend
           push: true
           tags: kanishka054/todo-app-backend:${{ github.sha }}
       - name: Deploy to the vm
         run: |
           echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
           mkdir -p /home/runner/.ssh
           ls /home/runner/.ssh
           chmod 700 /home/runner/ssh_key
           ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@13.235.24.208 -t "docker run --name todo_backend -d -p 8080:8080 kanishka054/todo-app-backend:${{ github.sha }}"   
